### ISSUE TITLE
Storing Data to Edex

### ISSUE THREAD

**Issue by keltonhalbert** [Unidata/python-awips#3]
I've found code and examples to store HDF5 data using pypies both in here and in the pythonPackages folder of the AWIPS2 github, and can successfully store the hdf5 data.

However, I have not found code or examples on how to update the database entries so that EDEX knows that the data is available for viewing. Is this possible using this package? Is it even possible at all?

Thanks,
Kelton.

**Comment by mjames-upc** [comment]
I understand that the DAF is a one-way interface and deliberately can not send data to the server.
